load("rules.bzl", "batch_execute_rule_regular_path", "batch_execute_rule_windows_path", "batch_print_execution_environment")

batch_execute_rule_windows_path(
    name = "batch_execute_rule_windows_path",
)

batch_execute_rule_regular_path(
    name = "batch_execute_rule_regular_path",
)

batch_print_execution_environment(
    name = "batch_print_execution_environment",
)
